default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8 
  database: gaucho_dev
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8 
  database: gaucho_test
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8 
  database: gaucho_prod
  username: root
  password: 1k6Ambigu
  host: localhost
